TASK789 - Contact Button
Maua-Dev/mauafood_front pull request #28
Opened 2023-01-12 20:30 UTC by Rodrigosiq03

2023-01-12 20:46 UTC, GabrielGodoy01 requested changes
- Criar widget especifico para o dialog

2023-01-12 22:47 UTC, GabrielGodoy01 requested changes
- Utilizar o módulo INTL para centralizar as strings

2023-01-13 02:21 UTC, Rodrigosiq03 commented
Terminar o review, atualizei os estilos do contact dialog

2023-01-13 17:17 UTC, GabrielGodoy01 approved these changes

2023-01-13 17:22 UTC, merged